### ISSUE TITLE
Subject name should now be in the config file, there should be only one config file and to be used by all subjects specified in a list

### ISSUE THREAD

**Issue by garikoitz** [dlinhardt/prfprepare#10]
I have this implemented in another repo, I will show and we can adapt (well, in fact we just need to add the launcher to that repository, the code is up and running)

**Comment by dlinhardt** [comment]
allowed for set subjects and sessions to "all" in the config file
3d189c35ba8bd05b3592e1bb2b8b17b9254b51a1
